package model;

import java.io.Serializable;

public class Parameters implements Serializable {
	// SUBSTITUTABILITY
	public Double SIGMA;
	
	// CAPITAL DYNAMICS PARAMETERS (7)
	public Double SAVINGS_RATE;
	public Double CAPITAL_CONVERSION_RATE; // Coefficient for the conversion of foregone consumption to capital
	public Double CAPITAL_EXPONENT;
	public Double DEPRECIATION_RATE;
	public Double CAPITAL_ENDOWMENT_MIN;
	public Double CAPITAL_ENDOWMENT_MAX;
	public Double CAPITAL_ENDOWMENT_SKEW_EXP;

	// AGENT BEHAVIOR PARAMETERS (5)
	public Integer AGENT_MEMORY_MAX;
	public Integer FRIENDS_MAX;
	public double SKILL_RETENTION_PROB_DECAY_RATE;
	public double SKILL_RETENTION_PROB_IN_USE;
	public Integer LEARNING_BY_DOING_FACTOR;

	// MONEY (2)
	public Double MONEY_ENDOWMENT_MIN;
	public Double MONEY_ENDOWMENT_MAX;
	
	// RETAILER BEHAVIOR PARAMETERS (35)
	public Double PROFIT_RATE;
	public Double RETAILER_TIME_COST;
	public Double MAX_RETAILER_EXIT_PROB_INCREMENT_DUE_TO_LOW_PAY;
	public Double MIN_RETAILER_EXIT_PROB_INCREMENT_DUE_TO_HIGH_PAY;
	public Double MIN_RETAILER_EXIT_PROB;
	public Double MAX_RETAILER_EXIT_PROB;
	public Double RETAILER_EXIT_PROB_INCREMENT_DUE_TO_NO_SALES;
	public Double THRESHOLD_CHOOSE_EMULATE;
	public Double THRESHOLD_CHOOSE_FRIENDS_MAKE;
	public Double THRESHOLD_CHOOSE_FRIENDS_CAN_MAKE;
	public Double THRESHOLD_CHOOSE_CAN_SELFSUPPLY_WHILE_RETAILING;
	public Double RETAILER_ENTRY_PROB_IF_RETAILERS_DOING_WORSE;
	public Double RETAILER_ENTRY_MULTIPLIER_FOR_LOG_UTIL_DIFFERENCE;
	public Double RETAILER_ENTRY_HANDICAP_FOR_LOG_UTIL_DIFFERENCE;
	public Double RETAILER_STARTING_PRICE_BIAS;
	public Double RETAILER_MAX_PRICE_DROP_BASED_ON_INCOME_SUPPLY_RATIO;
	public Double RETAILER_MAX_PRICE_RISE_BASED_ON_INCOME_SUPPLY_RATIO;
	public Double RETAILER_PRICE_SHIFT_MULTIPLIER_BASED_ON_CASH_INVENTORY_IMBALANCE;
	public Double RETAILER_PRICE_SHIFT_BIAS_BASED_ON_CASH_INVENTORY_IMBALANCE;
	public Double MAX_PRICE_CHANGE_BASED_ON_CASH_INVENTORY_IMBALANCE;
	public Double MIN_PRICE_CHANGE_BASED_ON_CASH_INVENTORY_IMBALANCE;
	public Double NORMAL_BUS_COND_PRICE_RANDOMIZATION_FACTOR;
	public Double ODDS_OF_MARKUP_CHANGE_UNDER_NORMAL_BUS_COND;
	public Double SIZE_OF_MARKUP_CHANGE_UNDER_NORMAL_BUS_COND;
	public Double ODDS_OF_MARKUP_CHANGE_UNDER_INVENTORY_PROBLEMS;
	public Double SIZE_OF_MARKUP_CHANGE_UNDER_INVENTORY_PROBLEMS;
	public Double ODDS_OF_MARKUP_CHANGE_UNDER_CASH_FLOW_PROBLEMS;
	public Double SIZE_OF_MARKUP_CHANGE_UNDER_CASH_FLOW_PROBLEMS;
	public Double RETAILER_MAX_PRICE_RESPONSE_TO_STOCKOUT;
	public Double RETAILER_STOCKOUT_RESPONSE_SKEW_EXP;
	public Double RETAILER_MAX_PRICE_RESPONSE_TO_CASHOUT;
	public Double RETAILER_CASHOUT_RESPONSE_SKEW_EXP;
	public Double RETAILER_MINIMUM_MARKUP;
	public Double RETAILER_PRICE_SETTING_RECENCY_WEIGHT_FACTOR;
	public Integer RETAILER_PRICE_SETTING_MAX_HINDSIGHT;
	public double MIN_STARTING_MARKUP;
	public double MAX_STARTING_MARKUP;
	
	public Object[] allValues;
	
	public Parameters() {
		// UTILTIY FUNCTION
		SIGMA=0.5;
		
		// CAPITAL DYNAMICS PARAMETERS (7)
		SAVINGS_RATE=0.0;
		CAPITAL_CONVERSION_RATE=0.1; // Coefficient for the conversion of foregone consumption to capital
		CAPITAL_EXPONENT=0.5;
		DEPRECIATION_RATE=0.0;
		CAPITAL_ENDOWMENT_MIN=1.0;
		CAPITAL_ENDOWMENT_MAX=1.0;
		CAPITAL_ENDOWMENT_SKEW_EXP=1.0;

		// AGENT BEHAVIOR PARAMETERS (5)
		AGENT_MEMORY_MAX=200;
		FRIENDS_MAX=10;
		SKILL_RETENTION_PROB_IN_USE=1;
		SKILL_RETENTION_PROB_DECAY_RATE=0.1;
		LEARNING_BY_DOING_FACTOR=5;

		// MONEY PARAMETERS (2)
		MONEY_ENDOWMENT_MIN=100.0;
		MONEY_ENDOWMENT_MAX=500.0;
		
		// RETAILER BEHAVIOR PARAMETERS (35)
		PROFIT_RATE=0.1;
		RETAILER_STARTING_PRICE_BIAS=-3.0;
		RETAILER_TIME_COST=0.5;
		MAX_RETAILER_EXIT_PROB_INCREMENT_DUE_TO_LOW_PAY=0.2;
		MIN_RETAILER_EXIT_PROB_INCREMENT_DUE_TO_HIGH_PAY=-0.2;
		MIN_RETAILER_EXIT_PROB=-3.0;
		MAX_RETAILER_EXIT_PROB=0.5;
		RETAILER_EXIT_PROB_INCREMENT_DUE_TO_NO_SALES=0.1;
		THRESHOLD_CHOOSE_EMULATE=0.2;
		THRESHOLD_CHOOSE_FRIENDS_MAKE=0.4;
		THRESHOLD_CHOOSE_FRIENDS_CAN_MAKE=0.6;
		THRESHOLD_CHOOSE_CAN_SELFSUPPLY_WHILE_RETAILING=0.8;
		RETAILER_ENTRY_PROB_IF_RETAILERS_DOING_WORSE=0.005;
		RETAILER_ENTRY_MULTIPLIER_FOR_LOG_UTIL_DIFFERENCE=0.25;
		RETAILER_ENTRY_HANDICAP_FOR_LOG_UTIL_DIFFERENCE=0.4;
		RETAILER_MAX_PRICE_DROP_BASED_ON_INCOME_SUPPLY_RATIO=0.2;
		RETAILER_MAX_PRICE_RISE_BASED_ON_INCOME_SUPPLY_RATIO=0.2;
		RETAILER_PRICE_SHIFT_MULTIPLIER_BASED_ON_CASH_INVENTORY_IMBALANCE=0.2;
		RETAILER_PRICE_SHIFT_BIAS_BASED_ON_CASH_INVENTORY_IMBALANCE=-0.2;
		MAX_PRICE_CHANGE_BASED_ON_CASH_INVENTORY_IMBALANCE=0.3;
		MIN_PRICE_CHANGE_BASED_ON_CASH_INVENTORY_IMBALANCE=-0.3;
		NORMAL_BUS_COND_PRICE_RANDOMIZATION_FACTOR=0.01;
		ODDS_OF_MARKUP_CHANGE_UNDER_NORMAL_BUS_COND=0.2;
		SIZE_OF_MARKUP_CHANGE_UNDER_NORMAL_BUS_COND=0.01;
		ODDS_OF_MARKUP_CHANGE_UNDER_INVENTORY_PROBLEMS=0.2;
		SIZE_OF_MARKUP_CHANGE_UNDER_INVENTORY_PROBLEMS=-0.01;
		ODDS_OF_MARKUP_CHANGE_UNDER_CASH_FLOW_PROBLEMS=0.2;
		SIZE_OF_MARKUP_CHANGE_UNDER_CASH_FLOW_PROBLEMS=-0.01;
		RETAILER_MAX_PRICE_RESPONSE_TO_STOCKOUT=3.0;
		RETAILER_STOCKOUT_RESPONSE_SKEW_EXP=3.0;
		RETAILER_MAX_PRICE_RESPONSE_TO_CASHOUT=0.75;
		RETAILER_CASHOUT_RESPONSE_SKEW_EXP=3.0;
		RETAILER_MINIMUM_MARKUP=0.1;
		RETAILER_PRICE_SETTING_RECENCY_WEIGHT_FACTOR=0.85;
		RETAILER_PRICE_SETTING_MAX_HINDSIGHT=10;
		MIN_STARTING_MARKUP=0.2;
		MAX_STARTING_MARKUP=0.8;
		recordValuesInVector();
	}
	
	public void recordValuesInVector() {
		
		// NOW PUT THEM ALL INTO allValues
		allValues=new Object[52];
		// SUBSTITUTABILITY
		allValues[0]= SIGMA;
		
		// CAPITAL DYNAMICS PARAMETERS (7)
		allValues[1]= SAVINGS_RATE;
		allValues[2]= CAPITAL_CONVERSION_RATE; // Coefficient for the conversion of foregone consumption to capital
		allValues[3]= CAPITAL_EXPONENT;
		allValues[4]= DEPRECIATION_RATE;
		allValues[5]= CAPITAL_ENDOWMENT_MIN;
		allValues[6]= CAPITAL_ENDOWMENT_MAX;
		allValues[7]= CAPITAL_ENDOWMENT_SKEW_EXP;

		// AGENT BEHAVIOR PARAMETERS
		allValues[8]= AGENT_MEMORY_MAX;
		allValues[9]= FRIENDS_MAX;
		allValues[10]=SKILL_RETENTION_PROB_IN_USE;
		allValues[11]=SKILL_RETENTION_PROB_DECAY_RATE;
		allValues[12]=LEARNING_BY_DOING_FACTOR;

		// ENDOWMENTS
		allValues[13]= MONEY_ENDOWMENT_MIN;
		allValues[14]= MONEY_ENDOWMENT_MAX;

		// RETAILER BEHAVIOR PARAMETERS
		allValues[15]= PROFIT_RATE;
		allValues[16]= RETAILER_TIME_COST;
		allValues[17]= MAX_RETAILER_EXIT_PROB_INCREMENT_DUE_TO_LOW_PAY;
		allValues[18]= MIN_RETAILER_EXIT_PROB_INCREMENT_DUE_TO_HIGH_PAY;
		allValues[19]= MIN_RETAILER_EXIT_PROB;
		allValues[20]= MAX_RETAILER_EXIT_PROB;
		allValues[21]= RETAILER_EXIT_PROB_INCREMENT_DUE_TO_NO_SALES;
		allValues[22]= THRESHOLD_CHOOSE_EMULATE;
		allValues[23]= THRESHOLD_CHOOSE_FRIENDS_MAKE;
		allValues[24]= THRESHOLD_CHOOSE_FRIENDS_CAN_MAKE;
		allValues[25]= THRESHOLD_CHOOSE_CAN_SELFSUPPLY_WHILE_RETAILING;
		allValues[26]= RETAILER_ENTRY_PROB_IF_RETAILERS_DOING_WORSE;
		allValues[27]= RETAILER_ENTRY_MULTIPLIER_FOR_LOG_UTIL_DIFFERENCE;
		allValues[28]= RETAILER_ENTRY_HANDICAP_FOR_LOG_UTIL_DIFFERENCE;
		allValues[29]= RETAILER_STARTING_PRICE_BIAS;
		allValues[30]= RETAILER_MAX_PRICE_DROP_BASED_ON_INCOME_SUPPLY_RATIO;
		allValues[31]= RETAILER_MAX_PRICE_RISE_BASED_ON_INCOME_SUPPLY_RATIO;
		allValues[32]= RETAILER_PRICE_SHIFT_MULTIPLIER_BASED_ON_CASH_INVENTORY_IMBALANCE;
		allValues[33]= RETAILER_PRICE_SHIFT_BIAS_BASED_ON_CASH_INVENTORY_IMBALANCE;
		allValues[34]= MAX_PRICE_CHANGE_BASED_ON_CASH_INVENTORY_IMBALANCE;
		allValues[35]= MIN_PRICE_CHANGE_BASED_ON_CASH_INVENTORY_IMBALANCE;
		allValues[36]= NORMAL_BUS_COND_PRICE_RANDOMIZATION_FACTOR;
		allValues[37]= ODDS_OF_MARKUP_CHANGE_UNDER_NORMAL_BUS_COND;
		allValues[38]= SIZE_OF_MARKUP_CHANGE_UNDER_NORMAL_BUS_COND;
		allValues[39]= ODDS_OF_MARKUP_CHANGE_UNDER_INVENTORY_PROBLEMS;
		allValues[40]= SIZE_OF_MARKUP_CHANGE_UNDER_INVENTORY_PROBLEMS;
		allValues[41]= ODDS_OF_MARKUP_CHANGE_UNDER_CASH_FLOW_PROBLEMS;
		allValues[42]= SIZE_OF_MARKUP_CHANGE_UNDER_CASH_FLOW_PROBLEMS;
		allValues[43]= RETAILER_MAX_PRICE_RESPONSE_TO_STOCKOUT;
		allValues[44]= RETAILER_STOCKOUT_RESPONSE_SKEW_EXP;
		allValues[45]= RETAILER_MAX_PRICE_RESPONSE_TO_CASHOUT;
		allValues[46]= RETAILER_CASHOUT_RESPONSE_SKEW_EXP;
		allValues[47]= RETAILER_MINIMUM_MARKUP;
		allValues[48]= RETAILER_PRICE_SETTING_RECENCY_WEIGHT_FACTOR;
		allValues[49]= RETAILER_PRICE_SETTING_MAX_HINDSIGHT;		
		allValues[50]= MIN_STARTING_MARKUP;
		allValues[51]= MAX_STARTING_MARKUP;
	}
	
	public Parameters clone() {
		Parameters p=new Parameters();
		p.SIGMA = SIGMA;
		  
		// CAPITAL DYNAMICS PARAMETERS (7)  
		p.SAVINGS_RATE = SAVINGS_RATE;
		p.CAPITAL_CONVERSION_RATE  = CAPITAL_CONVERSION_RATE; 
		p.CAPITAL_EXPONENT = CAPITAL_EXPONENT;
		p.DEPRECIATION_RATE = DEPRECIATION_RATE;
		p.CAPITAL_ENDOWMENT_MIN = CAPITAL_ENDOWMENT_MIN;
		p.CAPITAL_ENDOWMENT_MAX = CAPITAL_ENDOWMENT_MAX;
		p.CAPITAL_ENDOWMENT_SKEW_EXP = CAPITAL_ENDOWMENT_SKEW_EXP;
		  
		// AGENT BEHAVIOR PARAMETERS (5)  
		p.AGENT_MEMORY_MAX = AGENT_MEMORY_MAX;
		p.FRIENDS_MAX = FRIENDS_MAX;
		p.SKILL_RETENTION_PROB_DECAY_RATE = SKILL_RETENTION_PROB_DECAY_RATE;
		p.SKILL_RETENTION_PROB_IN_USE = SKILL_RETENTION_PROB_IN_USE;
		p.LEARNING_BY_DOING_FACTOR = LEARNING_BY_DOING_FACTOR;
		  
		// MONEY (2)  
		p.MONEY_ENDOWMENT_MIN = MONEY_ENDOWMENT_MIN;
		p.MONEY_ENDOWMENT_MAX = MONEY_ENDOWMENT_MAX;
		  
		// RETAILER BEHAVIOR PARAMETERS (35)  
		p.PROFIT_RATE = PROFIT_RATE;
		p.RETAILER_TIME_COST = RETAILER_TIME_COST;
		p.MAX_RETAILER_EXIT_PROB_INCREMENT_DUE_TO_LOW_PAY = MAX_RETAILER_EXIT_PROB_INCREMENT_DUE_TO_LOW_PAY;
		p.MIN_RETAILER_EXIT_PROB_INCREMENT_DUE_TO_HIGH_PAY = MIN_RETAILER_EXIT_PROB_INCREMENT_DUE_TO_HIGH_PAY;
		p.MIN_RETAILER_EXIT_PROB = MIN_RETAILER_EXIT_PROB;
		p.MAX_RETAILER_EXIT_PROB = MAX_RETAILER_EXIT_PROB;
		p.RETAILER_EXIT_PROB_INCREMENT_DUE_TO_NO_SALES = RETAILER_EXIT_PROB_INCREMENT_DUE_TO_NO_SALES;
		p.THRESHOLD_CHOOSE_EMULATE = THRESHOLD_CHOOSE_EMULATE;
		p.THRESHOLD_CHOOSE_FRIENDS_MAKE = THRESHOLD_CHOOSE_FRIENDS_MAKE;
		p.THRESHOLD_CHOOSE_FRIENDS_CAN_MAKE = THRESHOLD_CHOOSE_FRIENDS_CAN_MAKE;
		p.THRESHOLD_CHOOSE_CAN_SELFSUPPLY_WHILE_RETAILING = THRESHOLD_CHOOSE_CAN_SELFSUPPLY_WHILE_RETAILING;
		p.RETAILER_ENTRY_PROB_IF_RETAILERS_DOING_WORSE = RETAILER_ENTRY_PROB_IF_RETAILERS_DOING_WORSE;
		p.RETAILER_ENTRY_MULTIPLIER_FOR_LOG_UTIL_DIFFERENCE = RETAILER_ENTRY_MULTIPLIER_FOR_LOG_UTIL_DIFFERENCE;
		p.RETAILER_ENTRY_HANDICAP_FOR_LOG_UTIL_DIFFERENCE = RETAILER_ENTRY_HANDICAP_FOR_LOG_UTIL_DIFFERENCE;
		p.RETAILER_STARTING_PRICE_BIAS = RETAILER_STARTING_PRICE_BIAS;
		p.RETAILER_MAX_PRICE_DROP_BASED_ON_INCOME_SUPPLY_RATIO = RETAILER_MAX_PRICE_DROP_BASED_ON_INCOME_SUPPLY_RATIO;
		p.RETAILER_MAX_PRICE_RISE_BASED_ON_INCOME_SUPPLY_RATIO = RETAILER_MAX_PRICE_RISE_BASED_ON_INCOME_SUPPLY_RATIO;
		p.RETAILER_PRICE_SHIFT_MULTIPLIER_BASED_ON_CASH_INVENTORY_IMBALANCE = RETAILER_PRICE_SHIFT_MULTIPLIER_BASED_ON_CASH_INVENTORY_IMBALANCE;
		p.RETAILER_PRICE_SHIFT_BIAS_BASED_ON_CASH_INVENTORY_IMBALANCE = RETAILER_PRICE_SHIFT_BIAS_BASED_ON_CASH_INVENTORY_IMBALANCE;
		p.MAX_PRICE_CHANGE_BASED_ON_CASH_INVENTORY_IMBALANCE = MAX_PRICE_CHANGE_BASED_ON_CASH_INVENTORY_IMBALANCE;
		p.MIN_PRICE_CHANGE_BASED_ON_CASH_INVENTORY_IMBALANCE = MIN_PRICE_CHANGE_BASED_ON_CASH_INVENTORY_IMBALANCE;
		p.NORMAL_BUS_COND_PRICE_RANDOMIZATION_FACTOR = NORMAL_BUS_COND_PRICE_RANDOMIZATION_FACTOR;
		p.ODDS_OF_MARKUP_CHANGE_UNDER_NORMAL_BUS_COND = ODDS_OF_MARKUP_CHANGE_UNDER_NORMAL_BUS_COND;
		p.SIZE_OF_MARKUP_CHANGE_UNDER_NORMAL_BUS_COND = SIZE_OF_MARKUP_CHANGE_UNDER_NORMAL_BUS_COND;
		p.ODDS_OF_MARKUP_CHANGE_UNDER_INVENTORY_PROBLEMS = ODDS_OF_MARKUP_CHANGE_UNDER_INVENTORY_PROBLEMS;
		p.SIZE_OF_MARKUP_CHANGE_UNDER_INVENTORY_PROBLEMS = SIZE_OF_MARKUP_CHANGE_UNDER_INVENTORY_PROBLEMS;
		p.ODDS_OF_MARKUP_CHANGE_UNDER_CASH_FLOW_PROBLEMS = ODDS_OF_MARKUP_CHANGE_UNDER_CASH_FLOW_PROBLEMS;
		p.SIZE_OF_MARKUP_CHANGE_UNDER_CASH_FLOW_PROBLEMS = SIZE_OF_MARKUP_CHANGE_UNDER_CASH_FLOW_PROBLEMS;
		p.RETAILER_MAX_PRICE_RESPONSE_TO_STOCKOUT = RETAILER_MAX_PRICE_RESPONSE_TO_STOCKOUT;
		p.RETAILER_STOCKOUT_RESPONSE_SKEW_EXP = RETAILER_STOCKOUT_RESPONSE_SKEW_EXP;
		p.RETAILER_MAX_PRICE_RESPONSE_TO_CASHOUT = RETAILER_MAX_PRICE_RESPONSE_TO_CASHOUT;
		p.RETAILER_CASHOUT_RESPONSE_SKEW_EXP = RETAILER_CASHOUT_RESPONSE_SKEW_EXP;
		p.RETAILER_MINIMUM_MARKUP = RETAILER_MINIMUM_MARKUP;
		p.RETAILER_PRICE_SETTING_RECENCY_WEIGHT_FACTOR = RETAILER_PRICE_SETTING_RECENCY_WEIGHT_FACTOR;
		p.RETAILER_PRICE_SETTING_MAX_HINDSIGHT = RETAILER_PRICE_SETTING_MAX_HINDSIGHT;
		p.MIN_STARTING_MARKUP = MIN_STARTING_MARKUP;
		p.MAX_STARTING_MARKUP = MAX_STARTING_MARKUP;
		  
		p.recordValuesInVector();
		return p;
	}
	
	public static Parameters defaultValues() {
		Parameters p=new Parameters();
		return p;
	}
	
	public void transferVectorValuesToNamedVars() {
		boolean testing=false;
		Double[] numberValues=new Double[52];
		Y: for (int i=0; i<52; i++) {
			if (testing) System.out.println("TESTING Parameters.setParameters(). i="+i+". allValues[i].getClass()="
					+allValues[i].getClass().getSimpleName());
			if (allValues[i].getClass()==String.class) {
				String string=(String) allValues[i];
				numberValues[i]=Double.valueOf(string);
				continue Y;
			} else {
				if (allValues[i].getClass()==Integer.class) {
					Integer integer=(Integer) allValues[i];
					numberValues[i]=Double.valueOf(integer);
					continue Y;
				}
				else numberValues[i]=(Double) allValues[i];
			}
		}

		SIGMA=(Double) numberValues[0];
		
		// CAPITAL DYNAMICS PARAMETERS
		SAVINGS_RATE=(Double) numberValues[1];
		CAPITAL_CONVERSION_RATE=(Double) numberValues[2]; // Coefficient for the conversion of foregone consumption to capital
		CAPITAL_EXPONENT=(Double) numberValues[3];
		DEPRECIATION_RATE=(Double) numberValues[4];
		CAPITAL_ENDOWMENT_MIN=(Double) numberValues[5];
		CAPITAL_ENDOWMENT_MAX=(Double) numberValues[6];
		CAPITAL_ENDOWMENT_SKEW_EXP=(Double) numberValues[7];

		// AGENT BEHAVIOR PARAMETERS
		AGENT_MEMORY_MAX=(Integer) numberValues[8].intValue();
		FRIENDS_MAX=(Integer) numberValues[9].intValue();
		SKILL_RETENTION_PROB_IN_USE=(Double) numberValues[10];
		SKILL_RETENTION_PROB_DECAY_RATE=(Double) numberValues[11];
		LEARNING_BY_DOING_FACTOR=(Integer) numberValues[12].intValue();

		// ENDOWMENTS
		MONEY_ENDOWMENT_MIN=(Double) numberValues[13];
		MONEY_ENDOWMENT_MAX=(Double) numberValues[14];

		// RETAILER BEHAVIOR PARAMETERS
		PROFIT_RATE=(Double) numberValues[15];
		RETAILER_TIME_COST=(Double) numberValues[16];
		MAX_RETAILER_EXIT_PROB_INCREMENT_DUE_TO_LOW_PAY=(Double) numberValues[17];
		MIN_RETAILER_EXIT_PROB_INCREMENT_DUE_TO_HIGH_PAY=(Double) numberValues[18];
		MIN_RETAILER_EXIT_PROB=(Double) numberValues[19];
		MAX_RETAILER_EXIT_PROB=(Double) numberValues[20];
		RETAILER_EXIT_PROB_INCREMENT_DUE_TO_NO_SALES=(Double) numberValues[21];
		THRESHOLD_CHOOSE_EMULATE=(Double) numberValues[22];
		THRESHOLD_CHOOSE_FRIENDS_MAKE=(Double) numberValues[23];
		THRESHOLD_CHOOSE_FRIENDS_CAN_MAKE=(Double) numberValues[24];
		THRESHOLD_CHOOSE_CAN_SELFSUPPLY_WHILE_RETAILING=(Double) numberValues[25];
		RETAILER_ENTRY_PROB_IF_RETAILERS_DOING_WORSE=(Double) numberValues[26];
		RETAILER_ENTRY_MULTIPLIER_FOR_LOG_UTIL_DIFFERENCE=(Double) numberValues[27];
		RETAILER_ENTRY_HANDICAP_FOR_LOG_UTIL_DIFFERENCE=(Double) numberValues[28];
		RETAILER_STARTING_PRICE_BIAS=(Double) numberValues[29];
		RETAILER_MAX_PRICE_DROP_BASED_ON_INCOME_SUPPLY_RATIO=(Double) numberValues[30];
		RETAILER_MAX_PRICE_RISE_BASED_ON_INCOME_SUPPLY_RATIO=(Double) numberValues[31];
		RETAILER_PRICE_SHIFT_MULTIPLIER_BASED_ON_CASH_INVENTORY_IMBALANCE=(Double) numberValues[32];
		RETAILER_PRICE_SHIFT_BIAS_BASED_ON_CASH_INVENTORY_IMBALANCE=(Double) numberValues[33];
		MAX_PRICE_CHANGE_BASED_ON_CASH_INVENTORY_IMBALANCE=(Double) numberValues[34];
		MIN_PRICE_CHANGE_BASED_ON_CASH_INVENTORY_IMBALANCE=(Double) numberValues[35];
		NORMAL_BUS_COND_PRICE_RANDOMIZATION_FACTOR=(Double) numberValues[36];
		ODDS_OF_MARKUP_CHANGE_UNDER_NORMAL_BUS_COND=(Double) numberValues[37];
		SIZE_OF_MARKUP_CHANGE_UNDER_NORMAL_BUS_COND=(Double) numberValues[38];
		ODDS_OF_MARKUP_CHANGE_UNDER_INVENTORY_PROBLEMS=(Double) numberValues[39];
		SIZE_OF_MARKUP_CHANGE_UNDER_INVENTORY_PROBLEMS=(Double) numberValues[40];
		ODDS_OF_MARKUP_CHANGE_UNDER_CASH_FLOW_PROBLEMS=(Double) numberValues[41];
		SIZE_OF_MARKUP_CHANGE_UNDER_CASH_FLOW_PROBLEMS=(Double) numberValues[42];
		RETAILER_MAX_PRICE_RESPONSE_TO_STOCKOUT=(Double) numberValues[43];
		RETAILER_STOCKOUT_RESPONSE_SKEW_EXP=(Double) numberValues[44];
		RETAILER_MAX_PRICE_RESPONSE_TO_CASHOUT=(Double) numberValues[45];
		RETAILER_CASHOUT_RESPONSE_SKEW_EXP=(Double) numberValues[46];
		RETAILER_MINIMUM_MARKUP=(Double) numberValues[47];
		RETAILER_PRICE_SETTING_RECENCY_WEIGHT_FACTOR=(Double) numberValues[48];
		RETAILER_PRICE_SETTING_MAX_HINDSIGHT=(Integer) numberValues[49].intValue();		
		MIN_STARTING_MARKUP=(Double) numberValues[50];
		MAX_STARTING_MARKUP=(Double) numberValues[51];


	}
	
	public void setParameters(Economy e) {
		boolean testing=false;
		transferVectorValuesToNamedVars();
		
		// CAPITAL DYNAMICS PARAMETERS
		e.SAVINGS_RATE=SAVINGS_RATE;
		e.CAPITAL_CONVERSION_RATE=CAPITAL_CONVERSION_RATE; // Coefficient for the conversion of foregone consumption to capital
		e.CAPITAL_EXPONENT=CAPITAL_EXPONENT;
		e.DEPRECIATION_RATE=DEPRECIATION_RATE;
		e.CAPITAL_ENDOWMENT_MIN=CAPITAL_ENDOWMENT_MIN;
		e.CAPITAL_ENDOWMENT_MAX=CAPITAL_ENDOWMENT_MAX;
		e.CAPITAL_ENDOWMENT_SKEW_EXP=CAPITAL_ENDOWMENT_SKEW_EXP;

		// AGENT BEHAVIOR PARAMETERS
		e.AGENT_MEMORY_MAX=AGENT_MEMORY_MAX;
		e.FRIENDS_MAX=FRIENDS_MAX;
		e.SKILL_RETENTION_PROB_IN_USE=SKILL_RETENTION_PROB_IN_USE;
		e.SKILL_RETENTION_PROB_DECAY_RATE=SKILL_RETENTION_PROB_DECAY_RATE;
		e.LEARNING_BY_DOING_FACTOR=LEARNING_BY_DOING_FACTOR;

		// ENDOWMENTS
		e.MONEY_ENDOWMENT_MIN=MONEY_ENDOWMENT_MIN;
		e.MONEY_ENDOWMENT_MAX=MONEY_ENDOWMENT_MAX;
		
		// Retailer behavior parameters
		e.PROFIT_RATE=PROFIT_RATE;
		e.RETAILER_STARTING_PRICE_BIAS=RETAILER_STARTING_PRICE_BIAS;
		e.RETAILER_TIME_COST=RETAILER_TIME_COST;
		e.MAX_RETAILER_EXIT_PROB_INCREMENT_DUE_TO_LOW_PAY=MAX_RETAILER_EXIT_PROB_INCREMENT_DUE_TO_LOW_PAY;
		e.MIN_RETAILER_EXIT_PROB_INCREMENT_DUE_TO_HIGH_PAY=MIN_RETAILER_EXIT_PROB_INCREMENT_DUE_TO_HIGH_PAY;
		e.MIN_RETAILER_EXIT_PROB=MIN_RETAILER_EXIT_PROB;
		e.MAX_RETAILER_EXIT_PROB=MAX_RETAILER_EXIT_PROB;
		e.RETAILER_EXIT_PROB_INCREMENT_DUE_TO_NO_SALES=RETAILER_EXIT_PROB_INCREMENT_DUE_TO_NO_SALES;
		e.THRESHOLD_CHOOSE_EMULATE=THRESHOLD_CHOOSE_EMULATE;
		e.THRESHOLD_CHOOSE_FRIENDS_MAKE=THRESHOLD_CHOOSE_FRIENDS_MAKE;
		e.THRESHOLD_CHOOSE_FRIENDS_CAN_MAKE=THRESHOLD_CHOOSE_FRIENDS_CAN_MAKE;
		e.THRESHOLD_CHOOSE_CAN_SELFSUPPLY_WHILE_RETAILING=THRESHOLD_CHOOSE_CAN_SELFSUPPLY_WHILE_RETAILING;
		e.RETAILER_ENTRY_PROB_IF_RETAILERS_DOING_WORSE=RETAILER_ENTRY_PROB_IF_RETAILERS_DOING_WORSE;
		e.RETAILER_ENTRY_MULTIPLIER_FOR_LOG_UTIL_DIFFERENCE=RETAILER_ENTRY_MULTIPLIER_FOR_LOG_UTIL_DIFFERENCE;
		e.RETAILER_ENTRY_HANDICAP_FOR_LOG_UTIL_DIFFERENCE=RETAILER_ENTRY_HANDICAP_FOR_LOG_UTIL_DIFFERENCE;
		e.RETAILER_MAX_PRICE_DROP_BASED_ON_INCOME_SUPPLY_RATIO=RETAILER_MAX_PRICE_DROP_BASED_ON_INCOME_SUPPLY_RATIO;
		e.RETAILER_MAX_PRICE_RISE_BASED_ON_INCOME_SUPPLY_RATIO=RETAILER_MAX_PRICE_RISE_BASED_ON_INCOME_SUPPLY_RATIO;
		e.RETAILER_PRICE_SHIFT_MULTIPLIER_BASED_ON_CASH_INVENTORY_IMBALANCE=RETAILER_PRICE_SHIFT_MULTIPLIER_BASED_ON_CASH_INVENTORY_IMBALANCE;
		e.RETAILER_PRICE_SHIFT_BIAS_BASED_ON_CASH_INVENTORY_IMBALANCE=RETAILER_PRICE_SHIFT_BIAS_BASED_ON_CASH_INVENTORY_IMBALANCE;
		e.MAX_PRICE_CHANGE_BASED_ON_CASH_INVENTORY_IMBALANCE=MAX_PRICE_CHANGE_BASED_ON_CASH_INVENTORY_IMBALANCE;
		e.MIN_PRICE_CHANGE_BASED_ON_CASH_INVENTORY_IMBALANCE=MIN_PRICE_CHANGE_BASED_ON_CASH_INVENTORY_IMBALANCE;
		e.NORMAL_BUS_COND_PRICE_RANDOMIZATION_FACTOR=NORMAL_BUS_COND_PRICE_RANDOMIZATION_FACTOR;
		e.ODDS_OF_MARKUP_CHANGE_UNDER_NORMAL_BUS_COND=ODDS_OF_MARKUP_CHANGE_UNDER_NORMAL_BUS_COND;
		e.SIZE_OF_MARKUP_CHANGE_UNDER_NORMAL_BUS_COND=SIZE_OF_MARKUP_CHANGE_UNDER_NORMAL_BUS_COND;
		e.ODDS_OF_MARKUP_CHANGE_UNDER_INVENTORY_PROBLEMS=ODDS_OF_MARKUP_CHANGE_UNDER_INVENTORY_PROBLEMS;
		e.SIZE_OF_MARKUP_CHANGE_UNDER_INVENTORY_PROBLEMS=SIZE_OF_MARKUP_CHANGE_UNDER_INVENTORY_PROBLEMS;
		e.ODDS_OF_MARKUP_CHANGE_UNDER_CASH_FLOW_PROBLEMS=ODDS_OF_MARKUP_CHANGE_UNDER_CASH_FLOW_PROBLEMS;
		e.SIZE_OF_MARKUP_CHANGE_UNDER_CASH_FLOW_PROBLEMS=SIZE_OF_MARKUP_CHANGE_UNDER_CASH_FLOW_PROBLEMS;
		e.RETAILER_MAX_PRICE_RESPONSE_TO_STOCKOUT=RETAILER_MAX_PRICE_RESPONSE_TO_STOCKOUT;
		e.RETAILER_STOCKOUT_RESPONSE_SKEW_EXP=RETAILER_STOCKOUT_RESPONSE_SKEW_EXP;
		e.RETAILER_MAX_PRICE_RESPONSE_TO_CASHOUT=RETAILER_MAX_PRICE_RESPONSE_TO_CASHOUT;
		e.RETAILER_CASHOUT_RESPONSE_SKEW_EXP=RETAILER_CASHOUT_RESPONSE_SKEW_EXP;
		e.RETAILER_MINIMUM_MARKUP=RETAILER_MINIMUM_MARKUP;
		e.RETAILER_PRICE_SETTING_RECENCY_WEIGHT_FACTOR=RETAILER_PRICE_SETTING_RECENCY_WEIGHT_FACTOR;
		e.RETAILER_PRICE_SETTING_MAX_HINDSIGHT=RETAILER_PRICE_SETTING_MAX_HINDSIGHT;
		e.MIN_STARTING_MARKUP=MIN_STARTING_MARKUP;
		e.MAX_STARTING_MARKUP=MAX_STARTING_MARKUP;
	}

}
